# Generated by Django 5.0.4 on 2024-05-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.BooleanField()),
                ('patient_mbn', models.CharField(max_length=100)),
                ('patient_cnic', models.CharField(max_length=100)),
            ],
        ),
    ]
