import React, { useEffect, useState } from "react";
import api from "../../api";

const UserCashTally = () => {
  const [cashTally, setCashTally] = useState([]);
  const [userTsale, setUserTsale] = useState("");

  const fetchCashTally = async () => {
    const res = await api.get("api/u/cashTally/");

    if (res.status === 200) {
      console.log(res.data);
      setCashTally(res.data);
    } else {
      console.log(res.data);
    }
  };

  const fetchUserStats = async () => {
    const res = await api.get("api/u/userStats/");
    if (res.status === 200) {
      setUserTsale(res.data[0].totalSale);
    } else {
      console.log(res.data);
    }
  };

  useEffect(() => {
    fetchCashTally();
    fetchUserStats();
  }, []);

  return (
    <div className="h-full w-full flex flex-col items-center">
      <h1 className="text-lushText text-2xl font-bold mt-12"> Cash Tally </h1>
      <div className="h-96 w-1/2 mt-20 overflow-y-auto">
        <div className="relative overflow-x-auto">
          <table className="w-full text-sm text-left rtl:text-right text-lushText">
            <thead className="text-xs text-lushText uppercase bg-black">
              <tr>
                <th scope="col" className="px-6 py-3">
                  Id
                </th>
                <th scope="col" className="px-6 py-3">
                  Patient Name
                </th>
                <th scope="col" className="px-6 py-3">
                  Service Name
                </th>
                <th scope="col" className="px-6 py-3">
                  Service Price
                </th>
                <th scope="col" className="px-6 py-3">
                  Generated by
                </th>
              </tr>
            </thead>
            <tbody>
              {cashTally.map((value) => (
                <tr
                  className="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
                  key={value.id}
                >
                  <th
                    scope="row"
                    className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                  >
                    {value.id}
                  </th>
                  <td className="px-6 py-4">{value.patient_name}</td>
                  <td className="px-6 py-4">{value.service_name}</td>
                  <td className="px-6 py-4">{value.service_price}</td>
                  <td className="px-6 py-4">{value.user.username}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      <h1 className="text-lushText mt-16 text-2xl font-bold">
        Total Sale : {userTsale}
      </h1>
    </div>
  );
};

export default UserCashTally;
