# Generated by Django 5.0.4 on 2024-05-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lushCubesStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lushcubesstats',
            name='total_sale',
            field=models.BigIntegerField(),
        ),
    ]
