# Generated by Django 5.0.4 on 2024-05-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatsmodel',
            name='totalSale',
            field=models.BigIntegerField(),
        ),
    ]
